export const SOURCERA_CONVEX_BUILD_COMMIT_SHA: string =
  "__UNSTAMPED_CONVEX_BUILD__";
export const SOURCERA_CONVEX_BUILD_ENVIRONMENT: string =
  "__UNSTAMPED_CONVEX_ENVIRONMENT__";
export const SOURCERA_CONVEX_BUILD_PREVIEW_NAME: string =
  "__UNSTAMPED_CONVEX_PREVIEW_NAME__";
export const SOURCERA_CONVEX_PREVIEW_PROBE_TOKEN_SHA256: string =
  "__UNSTAMPED_CONVEX_PREVIEW_PROBE_TOKEN_SHA256__";
export const SOURCERA_CONVEX_PREVIEW_PROBE_EXPIRES_AT: number = 0;
